/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Jona622
 */
public class newAccFrame extends javax.swing.JFrame {

    /**
     * Creates new form newAccFrame
     */
    public newAccFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        fTextLabel = new javax.swing.JLabel();
        regUserLabel = new javax.swing.JLabel();
        regNameET = new javax.swing.JTextField();
        regNameLabel = new javax.swing.JLabel();
        regPhoneET = new javax.swing.JTextField();
        regEmailET = new javax.swing.JTextField();
        passLabel = new javax.swing.JLabel();
        phNumLabel = new javax.swing.JLabel();
        regPassET = new javax.swing.JPasswordField();
        regButton = new javax.swing.JButton();
        bgLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create new account.");
        setMaximumSize(new java.awt.Dimension(430, 443));
        setMinimumSize(new java.awt.Dimension(430, 443));
        setPreferredSize(new java.awt.Dimension(430, 443));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backButton.setBackground(java.awt.Color.blue);
        backButton.setForeground(java.awt.Color.white);
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 80, -1));

        fTextLabel.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        fTextLabel.setForeground(java.awt.Color.lightGray);
        fTextLabel.setText("Register new account:");
        getContentPane().add(fTextLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        regUserLabel.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        regUserLabel.setForeground(java.awt.Color.lightGray);
        regUserLabel.setText("Name:");
        getContentPane().add(regUserLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        regNameET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regNameETActionPerformed(evt);
            }
        });
        getContentPane().add(regNameET, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 270, -1));

        regNameLabel.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        regNameLabel.setForeground(java.awt.Color.lightGray);
        regNameLabel.setText("Email:");
        getContentPane().add(regNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));
        getContentPane().add(regPhoneET, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 270, -1));
        getContentPane().add(regEmailET, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 270, -1));

        passLabel.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        passLabel.setForeground(java.awt.Color.lightGray);
        passLabel.setText("Password:");
        getContentPane().add(passLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        phNumLabel.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        phNumLabel.setForeground(java.awt.Color.lightGray);
        phNumLabel.setText("Phone number:");
        getContentPane().add(phNumLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));
        getContentPane().add(regPassET, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 270, -1));

        regButton.setBackground(java.awt.Color.blue);
        regButton.setForeground(java.awt.Color.white);
        regButton.setText("Register");
        regButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regButtonActionPerformed(evt);
            }
        });
        getContentPane().add(regButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 100, -1));

        bgLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/bg.jpg"))); // NOI18N
        bgLabel.setMaximumSize(new java.awt.Dimension(430, 443));
        bgLabel.setMinimumSize(new java.awt.Dimension(430, 443));
        bgLabel.setPreferredSize(new java.awt.Dimension(430, 443));
        getContentPane().add(bgLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 450));
        bgLabel.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regNameETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regNameETActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regNameETActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        //loginFrame lg = new loginFrame();
        //lg.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void regButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regButtonActionPerformed
        // TODO add your handling code here:
        String name = regNameET.getText();
        String email = regEmailET.getText();
        String pass = regPassET.getText();
        String phone = regPhoneET.getText();
        new File("./Data").mkdirs();
        String ruta = "./Data/users.txt";
        File archivo = new File(ruta);
        BufferedWriter bw = null;
        BufferedReader br = null;
        boolean err = false;
        String aux;
        if (name.equals("") || email.equals("") || pass.equals("") || phone.equals("")) {
            JOptionPane.showMessageDialog(this, "Error: All fields are required", "ERROR", JOptionPane.ERROR_MESSAGE);
            err = true;
        } else {
            if (phone.length() != 13) {
                JOptionPane.showMessageDialog(this, "The number phone isn't valid. The longitude need to be of 13 digits.", "ERROR", JOptionPane.ERROR_MESSAGE);
                err = true;
                try {
                    long ph = Long.parseLong(phone);

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Error: Only numbers can be entered", "ERROR", JOptionPane.ERROR_MESSAGE);
                    err = true;
                    regPhoneET.setText("");
                }
            } else {
                //validar email unico
                try {
                    bw = new BufferedWriter(new FileWriter(archivo, true));
                    br = new BufferedReader(new FileReader(archivo));
                    while ((aux = br.readLine()) != null) {
                        if (aux.contains(email)) {
                            JOptionPane.showMessageDialog(this, "Error: The email is already registered.", "ERROR", JOptionPane.ERROR_MESSAGE);
                            err = true;
                            regEmailET.setText("");
                            break;
                        }
                    }
                } catch (IOException ex) {
                    Logger.getLogger(newAccFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                //----- validar archivo
                if (archivo.exists() && !err) {
                    try {                        
                        bw.write(name + "," + email + "," + pass + "," + phone + "\n");
                        //System.out.println("Titler"); //test
                        bw.close();
                    } catch (IOException ex) {
                        Logger.getLogger(newAccFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    JOptionPane.showMessageDialog(this, "Account created successfully \n", ruta, WIDTH);
                    this.dispose();
                    regNameET.setText("");
                    regEmailET.setText("");
                    regPassET.setText("");
                    regPhoneET.setText("");
                } else if (!archivo.exists() && !err) {
                    try {
                        bw.write(name + "," + email + "," + pass + "," + phone + "\n");
                        bw.close();
                    } catch (Exception e) {
                        Logger.getLogger(newAccFrame.class.getName()).log(Level.SEVERE, null, e);
                    }
                    JOptionPane.showMessageDialog(this, "Account created successfully \n", ruta, WIDTH);
                    this.dispose();
                    regNameET.setText("");
                    regEmailET.setText("");
                    regPassET.setText("");
                    regPhoneET.setText("");
                }
                //loginFrame lg = new loginFrame();
                //lg.setVisible(true);
            }

        }

    }//GEN-LAST:event_regButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newAccFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newAccFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newAccFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newAccFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newAccFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel bgLabel;
    private javax.swing.JLabel fTextLabel;
    private javax.swing.JLabel passLabel;
    private javax.swing.JLabel phNumLabel;
    private javax.swing.JButton regButton;
    private javax.swing.JTextField regEmailET;
    private javax.swing.JTextField regNameET;
    private javax.swing.JLabel regNameLabel;
    private javax.swing.JPasswordField regPassET;
    private javax.swing.JTextField regPhoneET;
    private javax.swing.JLabel regUserLabel;
    // End of variables declaration//GEN-END:variables
}
